# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write
        language: system
        types: [text]
        files: \.(json|markdown|md|yaml|yml)$

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell
        name: Codespell Spell Checker
        language: python
        types: [text]

  - repo: https://github.com/gitleaks/gitleaks
    rev: 39fdb480a06768cc41a84ef86959c07ff33091c4 # frozen: v8.28.0
    hooks:
      - id: gitleaks
